name: dispatch-a-workflow-demo
run-name: ${{ github.actor }} is testing out gihub acitions

on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$ENVE_VAR"
      - run: echo "$REPOVAR"
